/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_carpcap_order_calc_Calc */

#ifndef _Included_com_carpcap_order_calc_Calc
#define _Included_com_carpcap_order_calc_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_carpcap_order_calc_Calc
 * Method:    calcJni
 * Signature: (Ljava/lang/String;JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_carpcap_order_calc_Calc_calcJni
  (JNIEnv *, jclass, jstring, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
