server:
  port: 9002
eureka:
  client:
    fetch-registry: false #是否从Eureka中获取注册信息
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: order
ribbon:
  eager-load:
    enabled: true
