/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_carpcap_jni_JniDemo3 */

#ifndef _Included_com_carpcap_jni_JniDemo3
#define _Included_com_carpcap_jni_JniDemo3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_carpcap_jni_JniDemo3
 * Method:    compute
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_carpcap_jni_JniDemo3_compute
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
