server:
  name: spring
  port: 10001
  tomcat:
    threads:
      max: 200  #最大线程数
      min-spare: 10 #最小线程数
    max-connections: 8192 #最大连接数
    accept-count: 100 #最大等待数
    connection-timeout: 5000 #在Tomcat 7及更高版本中，默认的connection-timeout是20000（即20秒）  ,之前的版本是60000（60秒）